source-iterable: fix failing access check
After merging 32a68c514f544677ec6635d4a04f11973ef705c1, source-iterable captures started failing with:
TypeError: IterableExportStreamAdjustableRange.read_records() missing 1 required positional argument: 'cursor_field'

In that commit, I missed that the AccessCheck stream inherits from Users, and AccessCheck wasn't passing a `cursor_field` argument when it was used in the `read_full_refresh` helper function, causing the connector to fail. This commit fixes that by passing a `cursor_field` argument in the `read_full_refresh` function.