materialize-redshift: set temporary table varchar size (#4624)
The redshift connector resizes target tables according to the actual
size of document values, but the temporary table for store and delete
always uses TEXT, which is an alias for VARCHAR(256).  If the keys are
are longer than this they will be truncated when copied into the table.
This can result in the error during merge:
```
ERROR: Found multiple matches to update the same tuple. (SQLSTATE XX000)
```

With this change the varcharColumnMetas, set on startup from the actual
column definitions and potentially updated in Load, is used to size the
columns in the store and delete temporary tables.