materialize-redshift: add is not null to update statement
When updating a column with many rows and null values, we ran into the
error: 'Invalid input (SQLSTATE XX000)'

With psql the error was:
```
error:  Invalid input
  code:      8001
  context:   String value exceeds the max size of 65535 bytes
```

This was odd since the column only contained several short simple
strings:
```
 column    |   count
-----------+-----------
           | 426004506
 active    |   7177705
 unknown   |   2428474
 inactive  |   2459190
```

By skipping rows that are null the statement was able to complete.  In
order to add this check I broke out the update statement into one per
column.