materialize-snowflake: treat dual as reserved word (#4635)
In some database, including snowflake, there exists a special dual
table[1].  If you are materializing to a table with the same name and do
not fully qualify the path then it will try to use the built in table
which won't have the expected columns and you will see this error:
```
SQL compilation error: error line 2 at position 18 invalid identifier 'DUAL.FLOW_DOCUMENT'
```

There are a few ways I looked into fixing this.  I decided to add dual
to the reserved words so that it will be quoted.  This has the side
effect of changing the casing of the materialization table.

Another option is to fully qualified all identifiers in our statements.
This would be a pretty large change.

I also considered changing the resource path to include the schema, this
changes the path so the binding is treated as new.

[1]: https://en.wikipedia.org/wiki/DUAL_table